name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Specify the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Install vsce
      run: npm install -g vsce

    - name: Lint and build
      run: npm run compile # Ensure this script is defined in your package.json

    - name: Package Extension
      run: vsce package

    #- name: Publish Extension
    #  env:
    #    VSCODE_TOKEN: ${{ secrets.VSCODE_MARKET_PUBLISH_TOKEN }}
    #  run: vsce publish -p $VSCODE_TOKEN
